
# Composing nested config with default
defaults:
  - _self_
  - data: ftag  # Path to sub-config, can also omit the .yaml extension
  - trainer: default.yaml
  - model: classifier.yaml  # I add full path for easy navigation in vim (cursor in path, press gf)


# Global configurations shared between different modules
experiment: null
seed: 42
name: null